version: '3.8'

services:
  db:
    image: mysql:latest
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="root" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - petclinic-network

  app:
    image: petclinic:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/petclinic
      - SPRING_PROFILES_ACTIVE=mysql
    networks:
      - petclinic-network
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s

  load_balancer:
    image: nginx:latest
    volumes:
      - /home/mohamed/task1/spring-petclinic/conf.d:/etc/nginx/conf.d/
    ports:
      - 6020:80
    depends_on:
      - app
    networks:
      - petclinic-network

volumes:
  mysql-volume:

networks:
  petclinic-network:
    driver: bridge
