version: '3.8'

services:
  db:
    image: mysql:latest
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="root" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql-volume:/var/lib/mysql

  app:
    build:
      context: .
      target: dev
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/petclinic
      - SPRING_PROFILES_ACTIVE=mysql
    ports:
      - "3010:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql-volume:
